login = "Your Login"
password = "Your Password"
streamers = ["Streamer1","Streamer2"]
send_mesages = False
messages = ["Hello,streamer",":)","I'm Bot KEKW"]
load_cookies = False
silent = False
mute_audio = False
auto_160p = False
key_stop = 'end'
